services:
  db:
    image: postgres:15
    container_name: ristosmart_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ristosmart_network
  backend:
    build:
      context: ./backend
    container_name: ristosmart_backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MANAGER_USER=${MANAGER_USER}
      - MANAGER_PASSWORD=${MANAGER_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
    networks:
      - ristosmart_network

networks:
  ristosmart_network:
    driver: bridge

volumes:
  db_data: